ALTER TABLE users
  ADD COLUMN phone VARCHAR(50) DEFAULT NULL,
  ADD COLUMN date_of_birth DATE DEFAULT NULL,
  ADD COLUMN gender VARCHAR(50) DEFAULT NULL,
  ADD COLUMN address VARCHAR(500) DEFAULT NULL,
  ADD COLUMN emergency_contact VARCHAR(500) DEFAULT NULL,
  ADD COLUMN profile_picture VARCHAR(500) DEFAULT NULL;
